---
ID: "e12e056a-30d4-44e1-9951-d152e97e82ff"
Parent: "0c77276d-a087-4613-94ed-4e90adb1495e"
Template: "0c77276d-a087-4613-94ed-4e90adb1495e"
Path: /sitecore/templates/Dynamic Sitemap XML/Priority/Priority For Items/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T144234Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "bf783f93-1e04-413a-a8e4-f8da900a59ca"
      Hint: Priority
      Value: 0.5
