---
ID: "90aaa66c-4223-4fa5-9ac2-045974aa3123"
Parent: "5badc027-144b-4155-a5a8-8fdc475db62b"
Template: "5badc027-144b-4155-a5a8-8fdc475db62b"
Path: /sitecore/templates/Dynamic Sitemap XML/Change Frequency/Change Frequency Value/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T132156Z
    - ID: "5915b020-9030-4b22-be4f-c3c1f8c06d32"
      Hint: Value
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
