---
ID: "8ee05d58-8870-4a2b-8d57-f0e616175a0b"
Parent: "821b9fa0-bdf0-489d-9e98-dd549416aaa6"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Dynamic Sitemap XML/Dynamic Routing/Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160126T133615Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
