---
ID: "a788e475-e9e6-4c54-885d-e434a1b2afcc"
Parent: "20f9e1ca-39fc-4b43-b513-462885848fee"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Dynamic Sitemap XML/Site Configuration
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/earth2.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T132908Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
