---
ID: "5c00c26d-1320-418c-b31a-ebba4239cc67"
Parent: "eab6d9cb-dc0c-44a6-8188-e737b33dc87a"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/system/Modules/Dynamic Sitemap XML/Change Frequency Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{5BADC027-144B-4155-A5A8-8FDC475DB62B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160206T132054Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
